version: '3.6'

services:
  db:
    image: mysql:8.2
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE:${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD:${MYSQL_PASSWORD}
      - MYSQL_USER:${MYSQL_USER}
      - MYSQL_PASSWORD:${MYSQL_PASSWORD}
    volumes:
      - ./dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network  
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8181:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - app-network
  webserver:
    depends_on:
      - phpmyadmin
      - db
    image: nginx:1.27.0-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./webapp:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - ./certbot-etc:/etc/letsencrypt
    networks:
      - app-network
  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot-etc:/etc/letsencrypt
      - ./webapp:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email prince@cultivar1.com --agree-tos --no-eff-email --force-renewal -d cultivar1.com -d www.cultivar1.com
volumes:
  certbot-etc:
  webapp:
  dbdata:

networks:
  app-network:
    driver: bridge
