version: '3.7'
services:
  webserver:
    container_name: cultivar_server
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 80:8080
      - 443:8443
    environment:
      SSL_MODE: "full"
      SSL_PRIVATE_KEY_FILE: "/etc/letsencrypt/live/cultivar1.com/privkey.pem;"
      SSL_CERTIFICATE_FILE: "/etc/letsencrypt/live/cultivar1.com/fullchain.pem;"
    volumes:
      - ./webapp:/var/www/html/public
      - ./certs/:/etc/letsencrypt/live/cultivar1.com/
#      - ./vhost/:/etc/apache2/sites-available/
    networks:
      - app-network
    depends_on:
      - db
  db:
    image: mysql:8.3
    container_name: cultivar_database
    volumes:
      - ./database/mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - app-network
  phpmyadmin:
    container_name: cultivar_phpmyadmin
    image: phpmyadmin:5.2.1
    restart: always
    ports:
      - "8181:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - app-network
    depends_on:
      - db
  sql-runner:
    image: mysql:8.3
    command: ["mysql", "-h", "mysql", "-u", "root", "HenearkrxeRn0!#", "url_shortner"]
    volumes:
      - ./sql-scripts:/var/www/html/public/sql-scripts
    depends_on:
      - db
  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot-etc:/etc/letsencrypt
      - ./webapp:/var/www/html/public
    command: certonly --webroot --webroot-path=/var/www/html/public --email prince@cultivar1.com --agree-tos --no-eff-email --force-renewal -d cultivar1.com -d www.cultivar1.com
volumes:
  certbot-etc:
  webapp:
  dbdata:
networks:
  app-network:
    driver: bridge