version: '3'

services:
  webserver:
    image: nginx:1.27.0-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
    networks:
      - app-network
  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - public:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email renmer03@betopcorporation.com --agree-tos --no-eff-email --staging -d ifindrw.com -d www.ifindrw.com
volumes:
  certbot-etc:
  public:
  dbdata:

networks:
  app-network:
    driver: bridge